name: keg_manager
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  # --- ここを追加しました ---
  flutter_launcher_icons: ^0.13.1

# --- ここも新しく追加しました ---
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#F9F1F0"
  adaptive_icon_foreground: "assets/icon.png"

flutter:
  uses-material-design: true
  # --- アセット（画像）を読み込めるようにここも追加 ---
  assets:
    - assets/icon.png